# Generated by Django 5.2.7 on 2026-03-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('liga', models.CharField(blank=True, max_length=100, null=True)),
                ('home', models.CharField(max_length=100)),
                ('away', models.CharField(max_length=100)),
                ('h_gols_ft', models.IntegerField(blank=True, null=True)),
                ('a_gols_ft', models.IntegerField(blank=True, null=True)),
                ('h_gols_ht', models.IntegerField(blank=True, null=True)),
                ('a_gols_ht', models.IntegerField(blank=True, null=True)),
                ('h_escanteios', models.IntegerField(blank=True, null=True)),
                ('a_escanteios', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Histórico de Jogo',
                'verbose_name_plural': 'Histórico de Jogos',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='JogoDoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('hora', models.CharField(blank=True, max_length=10, null=True)),
                ('liga', models.CharField(blank=True, max_length=100, null=True)),
                ('home', models.CharField(max_length=100)),
                ('away', models.CharField(max_length=100)),
                ('odd_h', models.FloatField(blank=True, null=True)),
                ('odd_d', models.FloatField(blank=True, null=True)),
                ('odd_a', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Jogo do Dia',
                'verbose_name_plural': 'Jogos do Dia',
                'ordering': ['hora', 'liga'],
            },
        ),
    ]
