# Generated by Django 5.2.7 on 2026-03-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogododia',
            name='link_confronto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
